//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace psdLec.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int transaction_id { get; set; }
        public int customer_id { get; set; }
        public int product_id { get; set; }
        public int shipper_id { get; set; }
        public System.DateTime transaction_date { get; set; }
        public int transaction_status { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Product Product { get; set; }
        public virtual Shipper Shipper { get; set; }
    }
}
